version: "2"

linters:
  enable:
    - depguard
    - sloglint
  exclusions:
    paths:
      - internal/lax509
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "k8s.io/klog/v2"
              desc: "klog is forbidden, use log/slog instead"
            - pkg: "k8s.io/klog"
              desc: "klog is forbidden, use log/slog instead"
    sloglint:
      attr-only: true
      context: all
formatters:
  exclusions:
    paths:
      - internal/lax509
