name: Build POSIX Tesseract with ko

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-posix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Install ko
        uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push POSIX tesseract with ko
        run: |
          ko build ./cmd/tesseract/posix \
            --bare \
            --platform=linux/amd64 \
            --tags latest,${{ github.sha }}
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/tesseract

      - name: Output image reference
        run: |
          echo "Image pushed to: ghcr.io/${{ github.repository_owner }}/tesseract/posix:latest"
          echo "Image pushed to: ghcr.io/${{ github.repository_owner }}/tesseract/posix:${{ github.sha }}"
