name: 'Terragrunt format check'
on:
  - pull_request

permissions:
  contents: read

env:
  tofu_version: '1.10.2'
  tg_version: '0.83.2'

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@4ed5b7344c80315e5357f28f36159fc980bc2d5a # v3.4.0
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'deployment'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
