name: 'Terragrunt format check'
on:
  - pull_request

permissions:
  contents: read

env:
  tofu_version: '1.10.2'
  tg_version: '0.83.2'

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@53dbdc2c3d43e82bf3bae10b734a968196442bec # v3.2.0
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'deployment'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
